config/routes.rb
Rails.application.routes.draw do
  resources :pins
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "pins#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pin.rb
class Pin < ApplicationRecord
  has_one_attached :picture
  has_many_attached :images
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: %i[ show edit update destroy ]

  # GET /pins or /pins.json
  def index
    @pins = Pin.all
  end

  # GET /pins/1 or /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = Pin.new
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins or /pins.json
  def create
    @pin = Pin.new(pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: "Pin was successfully created." }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1 or /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: "Pin was successfully updated." }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1 or /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url, notice: "Pin was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pin_params
      params.require(:pin).permit(:title, :content, :picture, images: [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content="text/html; charset=UTF-8" http-equiv="Content-Type"
    title PictureTown
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
  body
    = yield

app/views/pins/_form.html.slim
= form_for @pin do |f|
  - if @pin.errors.any?
    #error_explanation
      h2 = "#{pluralize(@pin.errors.count, "error")} prohibited this pin from being saved:"
      ul
        - @pin.errors.full_messages.each do |message|
          li = message
  .field
    = f.label :title
    = f.text_field :title, class: "form-control", placeholder: "Add a title..."
  .field
    = f.label :content
    = f.text_field :content, class: "form-control", placeholder: "Add a content..."
  .field
    = f.label :picture
    = f.file_field :picture, class: "form-control"
  .field
    = f.label :images
    = f.file_field :images, multiple: true, class: "form-control"
  .actions = f.submit "Save", class: "btn btn-primary"

app/views/pins/edit.html.slim
.container.mt-5
  h1 Editing pin

  == render 'form'

  => link_to 'Show', @pin
  '|
  =< link_to 'Back', pins_path

app/views/pins/index.html.slim
.container
  h1.mt-5 Post your interest in the town!
  .row
    - @pins.each do |pin|
      .col-sm-3
        .card
          .card-body
            = image_tag pin.picture, size: "280x300" if pin.picture.present?
            h5.card-title = pin.title
            p.card-text = pin.content
            = link_to 'Show', pin, class: "btn btn-sm indigo-button text-white me-2"
            = link_to 'Edit', edit_pin_path(pin), class: "btn btn-sm teal-button text-white me-2"
            = link_to "Download", rails_blob_path(pin.picture, disposition: "attachment"), class: "btn btn-sm text-white orange-button me-2" if pin.picture.present?
            = link_to 'Destroy', pin, data: { confirm: 'Are you sure?' }, method: :delete, class: "btn btn-sm red-button text-white"
  br

  = link_to 'New Pin', new_pin_path

app/views/pins/new.html.slim
.container.mt-5
  h1 New pin

  == render 'form'

  = link_to 'Back', pins_path

app/views/pins/show.html.slim
.container.mt-5
  p#notice = notice

  strong Title:
  p
    = @pin.title
  strong Content:
  p
    = @pin.content

  - @pin.images.each do |image|
    = image_tag image

  => link_to 'Edit', edit_pin_path(@pin)
  '|
  =< link_to 'Back', pins_path